import type { Metadata } from "next";
import { Saira } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";
import { FilterContextProvider } from "@/contexts/filter-context";
import { Footer } from "@/components/footer";

const saira = Saira({
  weight: ['300', '400', '500', '600'],
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "capputeeno",
  description: "Generated by create next app",
};






export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={saira.className}>
        <FilterContextProvider>
          <Header></Header>
          {children}
          {/* <Footer/> */}
        </FilterContextProvider>

      </body>
    </html>
  );
}
